index:
   path: /
   controller: App\Controller\QuizzController::index

# profil:
#   path: /try/{age<\d+>?0}
#   controller: App\Controller\TryController::try
#   methods: [GET, POST]
  #  host: jsonquizz.com
  #  schemes: [http, https]
  # api.jsonquizz.com / www.jsonquizz.com
  # defaults: 
  #   age: 0
  # requirements:
  #   age: \d+

